title: Transcribe Audio
description: |
  Transcribe audio files using [OpenAI's Whisper](https://github.com/openai/whisper).
instructions: |
  You may upload audio files from a publically accessible URL or links from
  Google Drive, Dropbox, Mediafire, Wetransfer, or Facebook.  
  If you use a share link for a folder, it will process all audio files in that folder.

  Facebook videos are now supported, but not URLs that start with fb.watch. 
  If you have a fb.watch link, paste it in your browser and hit enter to load the video.
  Grab the full FB video link from there. 
  The correct URL will follow the format: https://www.facebook.com/watch/?v=57937975397&ref=sharing
  
  Transcribe Audio no longer supports YouTube videos because of new download blocking/ bot detection
  measures. 
  
  You may specify which [model](https://github.com/openai/whisper#available-models-and-languages) of whisper you would like to use. 
  Generally, the bigger the model the more accurate the transcription and the longer it will take to complete. Do note that the large model is 
  slower and if you have a really large set of files to transcribe, it may timeout and not complete. 
type: object
documents: []
properties:
  url:
    title: URL
    type: string
    format: uri
    description: >-
      A publically accessible audio file or a supported cloud storage share link
  access_level:
    title: Access level for uploaded documents
    type: string
    default: private
    enum:
      - private
      - organization
      - public
  project_id:
    title: Project ID
    type: integer
    description: Project ID of the project you would like to upload the documents to. 
  model: 
    title: Model
    type: string
    description: Whisper model to use for transcription.
    default: base
    enum:
      - tiny
      - base
      - small
      - medium
      - large
required:
  - url
  - model
categories:
  - ai
  - file
