title: Whisper
description: Transcribe an audio file using OpenAI's whisper
type: object
documents: []
properties:
  url:
    title: URL
    type: string
    format: uri
  title:
    title: Title
    type: string
  model:
    title: Model
    type: string
    enum:
      - tiny
      - base
      - small
      - medium
      - large
    description: One of tiny, base, small, medium or large, in order from quickest to most accurate.
    default: base
required:
  - url
  - title
