title: Transcribe Audio, powered by Whisper
description: >-
  Transcribe audio files using [OpenAI's Whisper](https://github.com/openai/whisper),
  an open source machine learning model.

  You may upload audio files from any publically accessible URL.  You may also
  use share links from Google Drive, Dropbox, Mediafire and Wetransfer.  If you
  use a share link for a folder, it will process all audio files in that folder.

type: object
documents: []
properties:
  url:
    title: URL
    type: string
    format: uri
    description: >-
      A publically accessible audio file or a supported cloud storage share link
required:
  - url
