title: Transcribe Audio, powered by Whisper
description: >-
  Transcribe audio files using [OpenAI's Whisper](https://github.com/openai/whisper),
  an open source machine learning model.

  You may upload audio files from any publically accessible URL.  You may also
  use share links from Google Drive, Dropbox, Mediafire, Wetransfer, or YouTube.  If you
  use a share link for a folder, it will process all audio files in that folder.
instructions: |
  You may upload audio files from any publically accessible URL.  You may also
  use share links from Google Drive, Dropbox, Mediafire, Wetransfer, or YouTube.  If you
  use a share link for a folder, it will process all audio files in that folder. 
  Provide a project ID you'd like to upload the documents to as well as specify what access
  level you would like the documents to be upon upload. 
type: object
documents: []
properties:
  url:
    title: URL
    type: string
    format: uri
    description: >-
      A publically accessible audio file or a supported cloud storage share link
  access_level:
    title: Access level for uploaded documents (public, private(default), organization)
    type: string
    default: private
  project_id:
    title: Project ID of the project you would like the documents uploaded to (optional)
    type: integer
required:
  - url
categories:
  - ai 
  - file
