title: Transcribe Audio
description: |
  Transcribe audio files using [OpenAI's Whisper](https://github.com/openai/whisper),
  an open source machine learning model.
instructions: |
  You may upload audio files from a publically accessible URL.  
  You may also use share links from Google Drive, Dropbox, Mediafire, Wetransfer, or YouTube.  
  If you use a share link for a folder, it will process all audio files in that folder.

  Facebook videos are now supported, but not URLs that start with fb.watch. 
  If you have a fb.watch link, paste it in your browser and hit enter to load the video.
  Grab the full FB video link from there. The correct URL will follow the format
  https://www.facebook.com/watch/?v=57937975397&ref=sharing
type: object
documents: []
properties:
  url:
    title: URL
    type: string
    format: uri
    description: >-
      A publically accessible audio file or a supported cloud storage share link
  access_level:
    title: Access level for uploaded documents
    type: string
    default: private
    enum:
      - private
      - organization
      - public
  project_id:
    title: Project ID
    type: integer
    description: Project ID of the project you would like to upload the documents to. 
required:
  - url
categories:
  - ai
  - file
