
name: Run Add-On
on: repository_dispatch

jobs:
  Install-FFMPG:
    steps:
      - run: sudo apt-get -y install ffmpeg
  Run-Add-On:
    uses: MuckRock/documentcloud-addon-workflows/.github/workflows/run-addon.yml@v1
    with:
      python-version: "3.9"
